/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab.pkg5control.de.nominas;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.nio.Buffer;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Elian
 */
public class frmVentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmVentanaPrincipal
     */
    
    private ListaEmpleados lista;
    
    public frmVentanaPrincipal() {
        initComponents();
        lista = new ListaEmpleados();
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenuBar1 = new javax.swing.JMenu();
        mniAgregarEmpleado = new javax.swing.JMenuItem();
        mniCalcularNomina = new javax.swing.JMenuItem();
        mniGuardarArchivo = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu5.setText("jMenu5");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JMenuBar1.setText("Menu");
        JMenuBar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuBar1ActionPerformed(evt);
            }
        });

        mniAgregarEmpleado.setText("Agregar Empleado");
        mniAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAgregarEmpleadoActionPerformed(evt);
            }
        });
        JMenuBar1.add(mniAgregarEmpleado);

        mniCalcularNomina.setText("Calcular Nomina");
        JMenuBar1.add(mniCalcularNomina);

        mniGuardarArchivo.setText("Guardar Archivo");
        mniGuardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGuardarArchivoActionPerformed(evt);
            }
        });
        JMenuBar1.add(mniGuardarArchivo);

        jMenuBar1.add(JMenuBar1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAgregarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniAgregarEmpleadoActionPerformed

    private void mniGuardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGuardarArchivoActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_mniGuardarArchivoActionPerformed

    private void JMenuBar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuBar1ActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == mniAgregarEmpleado){
            frmAgregarEmpleados frmAgregar = new frmAgregarEmpleados(lista);
            frmAgregar.setVisible(true);
        }else if (evt.getSource() == mniCalcularNomina){
            frmCalcularNomina frmCalcular = new frmCalcularNomina(lista);
            frmCalcular.setVisible(true);
        }else if (evt.getSource() == JMenuBar1){
            JFileChooser fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            
            int respuesta = fc.showOpenDialog(this);
            
            if(respuesta == JFileChooser.APPROVE_OPTION){
                File directorioElegido = fc.getSelectedFile();
                String nombre = directorioElegido.getName();
                try{
                    String contenido = lista.convertirTexto();
                    
                    File file = new File(nombre + "||" + "Nomina.txt");
                    file.createNewFile();
                    FileWriter fw = new FileWriter(file);
                    BufferedWriter bw = new BufferedWriter(fw);
                    
                    bw.write(contenido);
                    bw.close();
                    String texto = "El archivo de la Nomina.txt se ha creado en " + nombre;
                    JOptionPane.showMessageDialog(this, texto, "mensaje", JOptionPane.INFORMATION_MESSAGE);
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_JMenuBar1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuBar1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem mniAgregarEmpleado;
    private javax.swing.JMenuItem mniCalcularNomina;
    private javax.swing.JMenuItem mniGuardarArchivo;
    // End of variables declaration//GEN-END:variables
}
